In [2]:
vote_df = pd.read_csv('../data/2016-vote-fips-acp.csv')

In [3]:
electoral_df = pd.read_csv('../data/electoral_votes.csv')

In [11]:
vote_by_state = pd.pivot_table(vote_df, index='st_name', values=['trump','clinton'], aggfunc=np.sum)

In [17]:
vote_by_state.reset_index(inplace=True)

In [20]:
vote_electoral = vote_by_state.merge(electoral_df, left_on="st_name", right_on="State", how="left" )

In [21]:
vote_electoral['r_']

,st_name,clinton,trump,State,electoralVotesNumber,Pop
0,Alabama,729547,1318255,Alabama,9,4908621
1,Alaska,116181,163347,Alaska,3,734002
2,Arizona,1161167,1252401,Arizona,11,7378494
3,Arkansas,380494,684872,Arkansas,6,3038999
4,California,8753788,4483810,California,55,39937489
5,Colorado,1338870,1202484,Colorado,9,5845526
6,Connecticut,897572,673215,Connecticut,7,3563077
7,Delaware,235603,185127,Delaware,3,982895
8,Florida,4504975,4617886,Florida,29,21992985
9,Georgia,1877963,2089104,Georgia,16,10736059
10,Hawaii,266905,128848,Hawaii,4,1412687
11,Idaho,189765,409055,Idaho,4,1826156
12,Illinois,3090729,2146015,Illinois,20,12659682
13,Indiana,1033126,1557286,Indiana,11,6745354
14,Iowa,653669,800983,Iowa,6,3179849
15,Kansas,427005,671018,Kansas,6,2910357
16,Kentucky,628854,1202971,Kentucky,8,4499692
17,Louisiana,780154,1178638,Louisiana,8,4645184
18,Maine,357735,335593,Maine,4,1345790
19,Maryland,1677928,943169,Maryland,10,6083116
20,Massachusetts,1995196,1090893,Massachusetts,11,6976597
21,Michigan,2268839,2279543,Michigan,16,10045029
22,Minnesota,1367716,1322951,Minnesota,10,5700671
23,Mississippi,485131,700714,Mississippi,6,2989260
24,Missouri,1071068,1594511,Missouri,10,6169270
25,Montana,177709,279240,Montana,3,1086759
26,Nebraska,284494,495961,Nebraska,5,1952570
27,Nevada,539260,512058,Nevada,6,3139658
28,New Hampshire,348526,345790,New Hampshire,4,1371246
29,New Jersey,2148278,1601933,New Jersey,14,8936574
30,New Mexico,385234,319667,New Mexico,5,2096640
31,New York,4556124,2819534,New York,29,19440469
32,North Carolina,2189316,2362631,North Carolina,15,10611862
33,North Dakota,93758,216794,North Dakota,3,761723
34,Ohio,2394164,2841005,Ohio,18,11747694
35,Oklahoma,420375,949136,Oklahoma,7,3954821
36,Oregon,1002106,782403,Oregon,7,4301089
37,Pennsylvania,2926441,2970733,Pennsylvania,20,12820878
38,Rhode Island,252525,180543,Rhode Island,4,1056161
39,South Carolina,855373,1155389,South Carolina,9,5210095
40,South Dakota,117458,227721,South Dakota,3,903027
41,Tennessee,870695,1522925,Tennessee,11,6897576
42,Texas,3877868,4685047,Texas,38,29472295
43,Utah,310676,515231,Utah,6,3282115
44,Vermont,178573,95369,Vermont,3,628061
45,Virginia,1981473,1769443,Virginia,13,8626207
46,Washington,1742718,1221747,Washington,12,7797095
47,West Virginia,188794,489371,West Virginia,5,1778070
48,Wisconsin,1382536,1405284,Wisconsin,10,5851754
49,Wyoming,55973,174419,Wyoming,3,567025